# Generated by Django 3.2.25 on 2025-09-15 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sistemas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistemas.sistema', verbose_name='Sistema de Jogo')),
            ],
        ),
        migrations.CreateModel(
            name='ValorPericiaFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(default=0)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pericias', to='campanhas.ficha')),
                ('pericia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemas.pericia')),
            ],
            options={
                'unique_together': {('ficha', 'pericia')},
            },
        ),
        migrations.CreateModel(
            name='ValorAtributoFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(default=0)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemas.atributo')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='campanhas.ficha')),
            ],
            options={
                'unique_together': {('ficha', 'atributo')},
            },
        ),
    ]
